version: '3.8'
services:
  neo4j-upm-gaiax:
    image: neo4j:latest
    container_name: neo4j-upm-gaiax
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - neo4j-config/neo4j.env
    volumes:
      - ./neo4j-data/data:/data
      - ./neo4j-data/logs:/logs
      - ./neo4j-data/plugins:/plugins
      - ./neo4j-data/import:/var/lib/neo4j/import
      - ./neo4j-config/init_constraints.cypher:/var/lib/neo4j/import/init_constraints.cypher  # Montar el script de constraints

  neo4j-api-upm-gaiax:
    build: ./neo4j-api-upm-gaiax
    env_file:
      - neo4j-config/neo4j.env
    ports:
      - "8000:80"
    depends_on:
      - neo4j-upm-gaiax

  mongodb-upm-gaiax:
    image: mongo:latest # Usa la imagen oficial de MongoDB
    container_name: mongodb-upm-gaiax
    restart: always
    ports:
      - "27017:27017" # Expone el puerto de MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: upm # Usuario raíz
      MONGO_INITDB_ROOT_PASSWORD: upmgaiax # Contraseña raíz
    volumes:
      - ./mongo-data:/data/db # Persistencia de datos
